name:                p2pchat
version:             0.1.0.0
github:              "ob-fun-ws18/studienarbeit-p2pchat"
license:             BSD3
author:              "Brammer Chris, Gabler Wolfgang"
maintainer:          "example@example.com"
copyright:           "2018 Brammer, Gabler"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ob-fun-ws18/studienarbeit-p2pchat#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  p2pchat-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - p2pchat
    - network
    - bytestring
    - optparse-applicative

tests:
  p2pchat-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - p2pchat
